### ISSUE TITLE
Thesis template might not follow IEEEtran standard

### ISSUE THREAD

**Issue by hfk01** [Swepz/LaTeX-Templates#6]
The bibliography style (unsrtnat) in the thesis template (main.tex) does not follow the IEEEtran standard. 

When using bibtex references straight from google scholar the output is formatted not according to the IEEE standard.
E.g. it spells out the full first name of the author "Yuan Chen", when it is supposed to convert it to "Y. Chen".

**Comment by Swepz** [comment]
Resolved 
![image](https://github.com/Swepz/LaTeX-Templates/assets/32343381/3ecfa795-339c-444c-bb78-92f0228b6822)
